//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbComm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("73, 241, 252")]
        public global::System.Drawing.Color RxColor {
            get {
                return ((global::System.Drawing.Color)(this["RxColor"]));
            }
            set {
                this["RxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 0, 120")]
        public global::System.Drawing.Color TxColor {
            get {
                return ((global::System.Drawing.Color)(this["TxColor"]));
            }
            set {
                this["TxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("等线, 12pt")]
        public global::System.Drawing.Font RxTxFont {
            get {
                return ((global::System.Drawing.Font)(this["RxTxFont"]));
            }
            set {
                this["RxTxFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPtl01Hex {
            get {
                return ((bool)(this["UserPtl01Hex"]));
            }
            set {
                this["UserPtl01Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPtl02Hex {
            get {
                return ((bool)(this["UserPtl02Hex"]));
            }
            set {
                this["UserPtl02Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPtl03Hex {
            get {
                return ((bool)(this["UserPtl03Hex"]));
            }
            set {
                this["UserPtl03Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPtl04Hex {
            get {
                return ((bool)(this["UserPtl04Hex"]));
            }
            set {
                this["UserPtl04Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPtl05Hex {
            get {
                return ((bool)(this["UserPtl05Hex"]));
            }
            set {
                this["UserPtl05Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPtl06Hex {
            get {
                return ((bool)(this["UserPtl06Hex"]));
            }
            set {
                this["UserPtl06Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPtl07Hex {
            get {
                return ((bool)(this["UserPtl07Hex"]));
            }
            set {
                this["UserPtl07Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPtl08Hex {
            get {
                return ((bool)(this["UserPtl08Hex"]));
            }
            set {
                this["UserPtl08Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPtl09Hex {
            get {
                return ((bool)(this["UserPtl09Hex"]));
            }
            set {
                this["UserPtl09Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserPtl10Hex {
            get {
                return ((bool)(this["UserPtl10Hex"]));
            }
            set {
                this["UserPtl10Hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl01 {
            get {
                return ((string)(this["UserPtl01"]));
            }
            set {
                this["UserPtl01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl02 {
            get {
                return ((string)(this["UserPtl02"]));
            }
            set {
                this["UserPtl02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl03 {
            get {
                return ((string)(this["UserPtl03"]));
            }
            set {
                this["UserPtl03"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl04 {
            get {
                return ((string)(this["UserPtl04"]));
            }
            set {
                this["UserPtl04"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl05 {
            get {
                return ((string)(this["UserPtl05"]));
            }
            set {
                this["UserPtl05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl06 {
            get {
                return ((string)(this["UserPtl06"]));
            }
            set {
                this["UserPtl06"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl07 {
            get {
                return ((string)(this["UserPtl07"]));
            }
            set {
                this["UserPtl07"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl08 {
            get {
                return ((string)(this["UserPtl08"]));
            }
            set {
                this["UserPtl08"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl09 {
            get {
                return ((string)(this["UserPtl09"]));
            }
            set {
                this["UserPtl09"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl10 {
            get {
                return ((string)(this["UserPtl10"]));
            }
            set {
                this["UserPtl10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl01Not {
            get {
                return ((string)(this["UserPtl01Not"]));
            }
            set {
                this["UserPtl01Not"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl02Not {
            get {
                return ((string)(this["UserPtl02Not"]));
            }
            set {
                this["UserPtl02Not"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl03Not {
            get {
                return ((string)(this["UserPtl03Not"]));
            }
            set {
                this["UserPtl03Not"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl04Not {
            get {
                return ((string)(this["UserPtl04Not"]));
            }
            set {
                this["UserPtl04Not"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl05Not {
            get {
                return ((string)(this["UserPtl05Not"]));
            }
            set {
                this["UserPtl05Not"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl06Not {
            get {
                return ((string)(this["UserPtl06Not"]));
            }
            set {
                this["UserPtl06Not"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl07Not {
            get {
                return ((string)(this["UserPtl07Not"]));
            }
            set {
                this["UserPtl07Not"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl08Not {
            get {
                return ((string)(this["UserPtl08Not"]));
            }
            set {
                this["UserPtl08Not"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl09Not {
            get {
                return ((string)(this["UserPtl09Not"]));
            }
            set {
                this["UserPtl09Not"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPtl10Not {
            get {
                return ((string)(this["UserPtl10Not"]));
            }
            set {
                this["UserPtl10Not"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("编辑发送内容")]
        public string TxSend {
            get {
                return ((string)(this["TxSend"]));
            }
            set {
                this["TxSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("73, 241, 252")]
        public global::System.Drawing.Color ExtrudeColor {
            get {
                return ((global::System.Drawing.Color)(this["ExtrudeColor"]));
            }
            set {
                this["ExtrudeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RxHex {
            get {
                return ((bool)(this["RxHex"]));
            }
            set {
                this["RxHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TxHex {
            get {
                return ((bool)(this["TxHex"]));
            }
            set {
                this["TxHex"] = value;
            }
        }
    }
}
